AWSTemplateFormatVersion: 2010-09-09
Description: The Pipeline Stack for all Source, Build and Deploying of Rig

Parameters:
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
  GitHubUser:
    Type: String
  PipelineName:
    Type: String
    Default: rig-codepipeline
  CodePipelineServiceRole:
    Type: String
  CodeBuildProject:
    Type: String
  ArtifactBucket:
    Type: String

Resources:
  RigCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      ArtifactStore:
           Type: S3
           Location: !Ref ArtifactBucket
      RoleArn: !Ref CodePipelineServiceRole
      Stages:
        - Name: Source
          Actions:
            - Name: Infra
              ActionTypeId:
                Owner: AWS
                Category: Source
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                BranchName: !Ref GitHubBranch
                FullRepositoryId: !Sub ${GitHubUser}/${GitHubRepo}
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
                InputArtifacts:
                  - Name: AppArtifact
                OutputArtifacts:
                  - Name: BuildOutput
                RunOrder: 1