AWSTemplateFormatVersion: 2010-09-09
Description: Template for the RDS MySQL database for Rig

Parameters:
  Environment:
    Type: String
  AllocatedStorage:
    Type: Number
  AZ:
    Type: AWS::EC2::AvailabilityZone::Name
  DBSubnet1:
    Type: AWS::EC2::Subnet::Id
  DBSubnet2:
    Type: AWS::EC2::Subnet::Id
  DBInstanceClass:
    Type: String
  DBName:
    Type: String
  DBPort:
    Type: Number
  DBUser:
    Type: String
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  DBPassword:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: RDSInstancePassword
      Description: Secret that contains the RDS password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  RigDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group for Rig DB
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
      Tags:
        - Key: Name
          Value: Rig DB Subnet Group

  RigDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      AvailabilityZone: !Ref AZ
      DBInstanceIdentifier: !Sub rig-${Environment}-db
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref RigDBSubnetGroup
      Engine: mysql
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBPassword}:SecretString:password}}'
      Port: !Ref DBPort
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Rig-${Environment}-DB
