AWSTemplateFormatVersion: 2010-09-09
Description: Rig Landing Page S3 Bucket Policy - Allows Public Read Access

Parameters:
  BucketName:
    Type: String

Resources:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: String
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Action:
            - 's3:GetObject'
          Effect: Allow
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref BucketName
              - /*
          Principal: '*'

