AWSTemplateFormatVersion: 2010-09-09
Description: Rig's Frontend App Instance security group

Parameters:
  SGName:
    Type: String
  SGDescription:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  InboundCIDR:
    Type: String

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SGName
      GroupDescription: !Ref SGDescription
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref InboundCIDR
      Tags:
        - Key: Name
          Value: !Ref SGName